import {renderFeedCalendar,paymentState} from './feed-calendar.js';
import '@fontsource/noto-sans-thai/400.css';
import '@fontsource/noto-sans-thai/600.css';
import './style.css';
import './ui.css';
import {navigation,bindNavigation,decorateActions} from './ui.js';
import {layouts} from './layout.js';
import * as db from './data.js';
import {money,addDays,thaiDate,compareBatches,forecast,newEgg,daysBetween} from './domain.js';
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,selectedBatch='',selectedOrder='',month='2026-09',route='home',calendarAnchored=false;
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nav=[['home','⌂','ภาพรวม'],['farm','◈','สัตว์และฟาร์ม'],['feed','▤','บิลอาหารกลาง'],['analytics','⌁','วิเคราะห์ล็อต'],['finance','↗','แผนการเงิน'],['prices','◇','ราคาไข่'],['settings','⚙','ตั้งค่า']];
const features=[['01','สัตว์และฟาร์ม','ล็อตสัตว์ • ไข่รายวัน • เหตุการณ์','farm'],['02','บิลอาหารกลาง','วันครบดีล • ปฏิทิน • รายการอาหาร','feed'],['03','วิเคราะห์ล็อต','ชนิดเดียวกัน • ข้อมูลครบ • ปัจจัยแวดล้อม','analytics'],['04','แผนการเงิน','เงินแยกล็อต • กำไรเมื่อปลด • สมมติฐาน','finance'],['05','ราคาไข่กลาง','ชุดราคา • ราคา ณ ช่วงเวลา','prices'],['06','ระบบและสิทธิ์','ล็อกอินเดียว • Supabase • สถานะการเชื่อมต่อ','settings']];
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),4500)}
function field(label,name,value,type='number',extra=''){return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`}
function opts(list,value,label='name'){return list.map(b=>`<option value="${esc(b.id)}" ${b.id===value?'selected':''}>${esc(b[label])}</option>`).join('')}
function table(head,rows){return `<div class="table-scroll"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${head.length}">ยังไม่มีข้อมูล</td></tr>`}</tbody></table></div>`}
function stat(label,value,sub=''){return `<div class="stat"><span>${label}</span><strong>${value}</strong><small>${sub}</small></div>`}
function section(title,body){return `<section class="section"><header><h2>${title}</h2></header>${body}</section>`}
function batchSelector(id='batchSelect',ducks=false){const rows=ducks?data.batches.filter(b=>b.species_id==='duck'):data.batches;return `<label>ล็อตสัตว์<select id="${id}">${opts(rows,selectedBatch)}</select></label>`}
function calendar(){return renderFeedCalendar({month,orders:data.orders,today,selected:selectedOrder})}
function timeline(){if(!data.orders.length)return '<p>ยังไม่มีบิล</p>';const start=data.orders.map(o=>o.order_date).sort()[0],end=data.orders.map(o=>addDays(o.order_date,o.credit_days)).sort().at(-1),span=Math.max(1,daysBetween(start,end));return `<p class="muted">สเกลร่วม ${thaiDate(start)} – ${thaiDate(end)}</p>`+data.orders.map(o=>{const due=addDays(o.order_date,o.credit_days),x=daysBetween(start,o.order_date)/span*580,w=o.credit_days/span*580;return `<div class="timeline-row"><button class="text-button" data-order="${o.id}">${esc(o.feed_name)}</button><div class="time-track"><span>${thaiDate(o.order_date)}</span><svg class="time-line" viewBox="0 0 600 24" role="img" aria-label="ช่วงเครดิต ${o.credit_days} วัน"><line x1="0" x2="600" y1="12" y2="12" stroke="#e1e7df"/><rect x="${x}" y="7" width="${Math.max(3,w)}" height="10" fill="#9fbc83"/></svg><button draggable="true" class="drag-end" data-drag="${o.id}" title="ลากไปวันที่ในปฏิทิน">${thaiDate(due)} ↔</button></div><small>${o.credit_days} วัน · ${money(o.total)} บาท</small></div>`}).join('')||'<p>ยังไม่มีบิล</p>'}
function chart(rows){if(!rows.length)return '<p>ไม่มีข้อมูล</p>';const vals=rows.map(r=>r.net),min=Math.min(0,...vals),max=Math.max(1,...vals),points=rows.map((r,i)=>`${30+i*540/Math.max(1,rows.length-1)},${180-(r.net-min)/(max-min)*150}`).join(' ');return `<svg class="chart" viewBox="0 0 600 210" role="img" aria-label="กราฟประมาณกำไรสะสม"><line x1="30" x2="570" y1="${180-(0-min)/(max-min)*150}" y2="${180-(0-min)/(max-min)*150}" stroke="#ccd8d1"/><polyline points="${points}" fill="none" stroke="#178265" stroke-width="3"/><text x="30" y="205">เริ่มแผน</text><text x="490" y="205">วัน ${rows.at(-1).day}</text></svg>`}
function blocks(){const batch=data.batches.find(b=>b.id===selectedBatch)||data.batches[0],order=data.orders.find(o=>o.id===selectedOrder)||data.orders[0];selectedBatch=batch?.id||'';selectedOrder=order?.id||'';const recent=data.eggs.filter(x=>x.batch_id===selectedBatch).sort((a,b)=>b.log_date.localeCompare(a.log_date));return {
modules:section('พื้นที่ทำงาน',`<div class="module-grid">${features.map(([n,t,s,r])=>`<a class="module" href="#${r}"><span>${n} ↗</span><h3>${t}</h3><p>${s}</p></a>`).join('')}</div>`),
summary:section('ภาพรวมข้อมูล',`<div class="stats">${stat('ล็อตสัตว์',data.batches.length,'เข้าถึงได้ตามสิทธิ์')}${stat('บิลอาหาร',data.orders.length,'ยอดเอกสาร ไม่ใช่หนี้ค้าง')}${stat('วันบันทึกไข่',data.eggs.length,'รวมล็อตที่เข้าถึงได้')}</div><p class="callout">เงินและแผนแยกตามล็อตสัตว์ ไม่มีการโอนเงินข้ามล็อตอัตโนมัติ</p>`),
roadmap:section('ชุดพัฒนา 0.1',`<ul class="clean-list"><li>● ทดลองบันทึกไข่และเหตุการณ์</li><li>● สร้างบิลและปรับวันเครดิต</li><li>● จำลองกำไรและบันทึกแผน</li><li>◌ งานชำระ/สต็อกครบวงจร และ LINE/Push อยู่ในขั้นต่อไป</li></ul><p class="muted">ข้อมูลตัวอย่างเป็นข้อมูลสมมติ ไม่ใช่ข้อมูลจากฟาร์มจริง</p>`),
batches:section('ล็อตสัตว์',`${batchSelector()}<div class="batch-list">${data.batches.map(b=>`<button class="batch ${b.id===selectedBatch?'active':''}" data-batch="${b.id}"><span>${esc(b.name)}</span><small>${b.species_id==='duck'?'เป็ด':'ปลา'} · เริ่ม ${thaiDate(b.start_date)} · ${money(b.initial_qty)} ตัว</small></button>`).join('')}</div>`),
eggs:section('บันทึกไข่รายวัน',table(['วันที่','ไข่รวม','ไข่แตก','เป็ดมีชีวิต'],recent.slice(0,30).map(r=>`<tr><td>${thaiDate(r.log_date)}</td><td>${money(r.total)}</td><td>${money(r.broken)}</td><td>${r.live_count==null?'ไม่ทราบ':money(r.live_count)}</td></tr>`))),
eggForm:section('บันทึก / แก้ไขไข่',batch?.species_id!=='duck'?'<p>ฟอร์มไข่ใช้เฉพาะล็อตเป็ด</p>':`<form id="eggForm"><p>${esc(batch?.name)}</p>${field('วันที่','log_date',today,'date','required') }<div class="form-grid">${field('ไข่รวม','total',0,'number','min="0" step="1" required')}${field('ไข่แตก','broken',0,'number','min="0" step="1" required')}${field('เป็ดมีชีวิต','live_count',batch?.initial_qty||0,'number','min="0" step="1" required')}</div><p class="muted" id="eggEditHint">เลือกวันที่เพื่อโหลดค่าที่บันทึกไว้ก่อนแก้ไข</p><button class="primary">บันทึกไข่</button></form>`),
events:section('เหตุการณ์และสภาพแวดล้อม',`<div class="event-list">${data.events.filter(e=>e.batch_id===selectedBatch).map(e=>`<p><small>${thaiDate(e.start_date)}</small><br>${esc(e.title)}</p>`).join('')||'<p>ยังไม่มีเหตุการณ์</p>'}</div><form id="eventForm">${field('เหตุการณ์','title','','text','required maxlength="200"')}${field('วันที่','start_date',today,'date','required')}<label>ประเภท<select name="event_type"><option value="weather">สภาพอากาศ</option><option value="medication">ให้ยา / วัคซีน</option><option value="other">อื่น ๆ</option></select></label><button>เพิ่มเหตุการณ์</button></form>`),
calendar:section('ปฏิทินครบดีล',calendar()),orders:section('รายการล็อตและแก้วันครบดีล',timeline()),
orderForm:section('เพิ่มบิลอาหาร',`<form id="orderForm">${field('ชื่ออาหาร','feed_name','','text','required maxlength="200"')}${field('วันที่สั่ง','order_date',today,'date','required')}<div class="form-grid">${field('เครดิต (วัน)','credit_days',25,'number','min="0" max="3650" required')}${field('จำนวน','quantity',200,'number','min="0.001" step="0.001" required')}${field('หน่วย','unit','กระสอบ','text','required')}${field('กก./หน่วย (ไม่ทราบเว้นว่าง)','kg_per_unit','','number','min="0.001" step="0.001"')}${field('ยอดบิล (บาท)','total',160000,'number','min="0" step="0.01" required')}</div><output id="duePreview"></output><button class="primary">สร้างบิล</button></form>`),
deal:section('รายละเอียดบิลที่เลือก',order?`<h3>${esc(order.feed_name)}</h3><div class="stats">${stat('วันที่สั่ง',thaiDate(order.order_date))}${stat('ครบดีล',thaiDate(addDays(order.order_date,order.credit_days)))}${stat('ยอดค้าง',paymentState(order,today).outstanding==null?'ไม่ทราบ':money(paymentState(order,today).outstanding),paymentState(order,today).label)}</div><form id="dealForm">${field('เครดิตใหม่ (วัน)','credit_days',order.credit_days,'number','min="0" max="3650" required')}<button>บันทึกเครดิตใหม่</button></form><p class="muted">มีประวัติแก้ไขเมื่อเชื่อมฐานข้อมูลจริง · การชำระเงินจริงยังไม่เปิดในหน้ารุ่นนี้</p>`:'<p>เลือกบิลจากปฏิทิน</p>'),
comparison:section('เปรียบเทียบล็อตชนิดเดียวกัน',`<label>ชนิดสัตว์<select id="speciesSelect"><option value="duck">เป็ด</option><option value="fish">ปลา</option></select></label><div id="comparisonOutput"></div><p class="muted">รุ่น 0.1 เทียบข้อมูลรายวันที่มีในชุดโหลด ยังไม่จัดแนวช่วงอายุอัตโนมัติ</p>`),
factors:section('อาหาร หรือปัจจัยอื่น?',`<p>การวิเคราะห์เชิงสาเหตุยังไม่เปิดใช้ในรุ่นนี้</p><ul class="clean-list"><li>อายุ ณ วันที่กินอาหาร</li><li>สูตรและเลขล็อตผลิต</li><li>ปริมาณกินจริง / อาหารเหลือ</li><li>ฝน ความร้อน ยา และการย้ายเล้า</li><li>ความครบถ้วนของวันที่บันทึก</li></ul><p class="callout">การลดลงพร้อมกับเปลี่ยนอาหารยังไม่ยืนยันว่าอาหารเป็นสาเหตุ ต้องเทียบปัจจัยร่วมและช่วงเวลาตอบสนอง</p>`),
forecast:section('กำไรคาดการณ์เมื่อปลด',`${batchSelector('planBatch')}<div id="forecastOutput"></div><h3>แผนที่บันทึก</h3><div id="savedPlans">${data.plans.filter(p=>p.batch_id===selectedBatch).map(p=>`<p>${esc(p.name)} · เป้าหมาย ${money(p.target_profit)} บาท</p>`).join('')||'<p class="muted">ยังไม่มีแผน</p>'}</div>`),
assumptions:section('สมมติฐานรายล็อต',`<form id="planForm"><div class="form-grid">${field('จำนวนเป็ด','count',batch?.initial_qty||3000)}${field('จำนวนวันในแผน','days',360)}${field('วันเริ่มไข่ในแผน','layStart',30)}${field('อัตราไข่ (%)','layRate',80,'number','max="100" step="0.1"')}${field('ราคาไข่/ฟอง','eggPrice',4,'number','step="0.01"')}${field('อาหาร กก./ตัว/วัน','feedKg',0.15,'number','step="0.001"')}${field('อาหาร บาท/กก.','feedPrice',16,'number','step="0.01"')}${field('ค่าใช้จ่ายอื่น/วัน','dailyExpense',500)}${field('ทุนสัตว์/ค่าเริ่มต้น ไม่รวมอาหารซ้ำ','investment',300000)}${field('รายรับขายปลดสุทธิ','salvage',180000)}${field('กำไรเป้าหมาย','target',500000)}</div><p class="muted">แบบจำลองค่าคงที่รุ่นแรก ไม่รวมเครดิต/จังหวะรับจ่าย และยังไม่ใช่ยอดเงินเก็บจริง</p><button class="primary">บันทึกแผนของล็อตนี้</button></form>`),
prices:section('ราคาไข่ที่เข้าถึงได้',table(['เกรด','ราคา','เริ่มใช้'],data.prices.map(p=>`<tr><td>${esc(p.grade)}</td><td>${money(p.price)}</td><td>${thaiDate(p.valid_from)}</td></tr>`))),
priceNotes:section('หลักการราคา',`<p>ราคาที่ขายจริงเก็บในรายการขาย ไม่เปลี่ยนตามราคากลางย้อนหลัง</p><p class="muted">หน้านี้อ่านข้อมูลได้ ส่วนหน้าจัดการชุดราคาและช่วงราคาจะเพิ่มในขั้นต่อไป</p>`),
connect:section('การเชื่อมต่อ',`<p>${db.live?'เชื่อม Supabase โปรเจกต์ใหม่ตาม config.js':'โหมดทดลอง ไม่เชื่อมฐานข้อมูลจริง'}</p><p>ตั้งค่า URL และ publishable key ของโปรเจกต์ใหม่ใน <code>config.js</code> หลังรัน SQL และตั้ง Google Login</p>${db.live?'<button id="logout">ออกจากระบบ</button>':'<button id="reset">ล้างเฉพาะข้อมูลตัวอย่างในเครื่องนี้</button>'}<p class="muted">ห้ามใส่ service-role หรือ secret key ใน frontend</p>`),
status:section('สถานะการติดตั้ง',`<ul class="clean-list"><li>App shell / manifest / service worker: มีแล้ว</li><li>Push: มีตัวรับ แต่ยังไม่มีบริการส่งที่ตั้งค่าแล้ว</li><li>LINE / Drive: ยังไม่เชื่อมระบบจริง</li><li>Offline ข้อมูลจริง: ยังไม่เปิด queue เขียน</li><li>ฐานข้อมูลเดิม: ไม่มีการแก้ไข</li></ul><p>เวอร์ชัน 0.1.2 • 1 ตุลาคม 2569</p>`)
}}
async function reload(){data=await db.load();if(!calendarAnchored&&data.orders.length){const ordered=[...data.orders].sort((a,b)=>a.order_date.localeCompare(b.order_date));const anchor=ordered.find(o=>paymentState(o,today).tone!=='paid')||ordered.at(-1);selectedOrder=anchor.id;month=anchor.order_date.slice(0,7);calendarAnchored=true;}render()}
function render(){route=location.hash.slice(1)||'home';if(!layouts[route])route='home';const b=blocks(),l=layouts[route];$('#app').innerHTML=`${navigation(nav,route)}<main><header class="topbar"><div><small>DUCKY / ${db.live?'CONNECTED':'DEMO WORKSPACE'}</small><h1>${nav.find(n=>n[0]===route)[2]}</h1></div><span class="status-dot">${navigator.onLine?'ออนไลน์':'ออฟไลน์'}</span></header><div class="mode-banner">${db.live?'ข้อมูลตามสิทธิ์บัญชีของคุณ':'โหมดทดลอง • ข้อมูลสมมติ • บันทึกในเครื่องนี้เท่านั้น'}</div><div class="workspace ${l.ratio}"><div class="zone zone-left">${l.left.map(k=>b[k]).join('')}</div><div class="zone zone-right">${l.right.map(k=>b[k]).join('')}</div></div><footer>ระบบใหม่แยกจาก GAS เดิม · รุ่นพัฒนา 0.1.2</footer></main>`;bind();bindNavigation();decorateActions();}
function on(id,event,fn){const el=$(id);if(el)el.addEventListener(event,fn)}
async function submit(e,fn){e.preventDefault();if(db.live&&!navigator.onLine){toast('ออฟไลน์: ยังส่งข้อมูลจริงไม่ได้');return}const btn=e.target.querySelector('button');btn.disabled=true;try{await fn(Object.fromEntries(new FormData(e.target)));await reload();toast('บันทึกสำเร็จ')}catch(err){toast(err.message)}finally{btn.disabled=false}}
function bind(){document.querySelectorAll('[data-batch]').forEach(el=>el.onclick=()=>{selectedBatch=el.dataset.batch;render()});on('#batchSelect','change',e=>{selectedBatch=e.target.value;render()});on('#planBatch','change',e=>{selectedBatch=e.target.value;render()});document.querySelectorAll('[data-order]').forEach(el=>el.onclick=()=>{selectedOrder=el.dataset.order;render()});
let eggVersion=0;function loadEgg(){const f=$('#eggForm');if(!f)return;const r=data.eggs.find(x=>x.batch_id===selectedBatch&&x.log_date===f.elements.log_date.value);eggVersion=r?.version||0;if(r){for(const k of ['total','broken','live_count'])f.elements[k].value=r[k]??'';}else{f.elements.total.value=0;f.elements.broken.value=0;}$('#eggEditHint').textContent=r?'กำลังแก้รายการเดิม • ตรวจเวอร์ชันก่อนบันทึก':'รายการใหม่';}on('#eggForm input[name=log_date]','change',loadEgg);loadEgg();
on('#eggForm','submit',e=>submit(e,v=>db.saveEgg(newEgg({...v,batch_id:selectedBatch,total:+v.total,broken:+v.broken,live_count:+v.live_count,version:eggVersion}))));on('#eventForm','submit',e=>submit(e,v=>db.saveEvent({...v,batch_id:selectedBatch})));
function preview(){const f=$('#orderForm');try{$('#duePreview').textContent='ครบดีล '+thaiDate(addDays(f.elements.order_date.value,+f.elements.credit_days.value))}catch{}}on('#orderForm','input',preview);if($('#orderForm'))preview();on('#orderForm','submit',e=>submit(e,v=>db.saveOrder({...v,id:crypto.randomUUID(),credit_days:+v.credit_days,quantity:+v.quantity,kg_per_unit:v.kg_per_unit?+v.kg_per_unit:null,total:+v.total,version:0})));
on('#dealForm','submit',e=>submit(e,v=>db.saveOrder({...data.orders.find(o=>o.id===selectedOrder),credit_days:+v.credit_days})));
on('#lotMonth','click',()=>{const o=data.orders.find(o=>o.id===selectedOrder);if(o){month=o.order_date.slice(0,7);render()}});on('#currentMonth','click',()=>{month=today.slice(0,7);render()});
for(const [id,delta]of [['#prevMonth',-1],['#nextMonth',1]])on(id,'click',()=>{const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+delta);month=d.toISOString().slice(0,7);render()});
document.querySelectorAll('[data-drag]').forEach(el=>el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.drag));document.querySelectorAll('[data-date]').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=async e=>{e.preventDefault();const o=data.orders.find(o=>o.id===e.dataTransfer.getData('text/plain'));if(!o)return;const n=daysBetween(o.order_date,el.dataset.date);if(n<0||n>3650)return toast('วันครบดีลต้องไม่ก่อนวันสั่ง');if(!confirm(`เปลี่ยนวันครบดีลจาก ${thaiDate(addDays(o.order_date,o.credit_days))} เป็น ${thaiDate(el.dataset.date)}?`))return;try{await db.saveOrder({...o,credit_days:n});await reload();toast('แก้วันครบดีลแล้ว')}catch(err){toast(err.message)}}});
function comparison(){const species=$('#speciesSelect').value,bs=data.batches.filter(b=>b.species_id===species);try{const rows=compareBatches(bs,data.eggs);$('#comparisonOutput').innerHTML=table(['ล็อต','วันที่มีข้อมูล','ไข่รวม','อัตราไข่ถ่วงน้ำหนัก'],rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.days}</td><td>${money(r.eggs)}</td><td>${r.rate===null?'ไม่ทราบ':r.rate.toFixed(1)+'% ('+r.rate_days+' วัน)'}</td></tr>`))}catch(e){$('#comparisonOutput').textContent=e.message}}on('#speciesSelect','change',comparison);if($('#speciesSelect'))comparison();
function parameters(){return Object.fromEntries([...new FormData($('#planForm'))].map(([k,v])=>[k,+v]))}function recalc(){try{if(data.batches.find(b=>b.id===selectedBatch)?.species_id!=='duck'){throw Error('แบบจำลองรุ่นนี้รองรับเป็ดเท่านั้น แบบจำลองปลาจะเพิ่มภายหลัง')}const p=parameters(),r=forecast(p);$('#forecastOutput').innerHTML=`<div class="stats">${stat('กำไรเมื่อปลด',money(r.finalNet),'บาท • ประมาณการ')}${stat('เทียบเป้าหมาย',money(-r.gap),'บาท')}${stat('คืนทุนก่อนขายปลด',r.breakEven?'วันที่ '+r.breakEven:'ยังไม่ถึง')}</div>${chart(r.rows)}<p class="callout">แผนนี้เป็นของ ${esc(data.batches.find(b=>b.id===selectedBatch)?.name)} เท่านั้น</p>`}catch(e){$('#forecastOutput').textContent=e.message}}on('#planForm','input',recalc);if($('#planForm'))recalc();on('#planForm','submit',e=>submit(e,()=>{const a=parameters();forecast(a);if(data.batches.find(b=>b.id===selectedBatch)?.species_id!=='duck')throw Error('แบบจำลองไข่ใช้กับเป็ดเท่านั้น');return db.savePlan({batch_id:selectedBatch,name:'แผน '+thaiDate(today),start_date:today,end_date:addDays(today,a.days-1),target_profit:a.target,assumptions:a})}));on('#reset','click',()=>{if(confirm('ล้างข้อมูลตัวอย่าง?'))db.resetDemo()});on('#logout','click',()=>db.logout().catch(e=>toast(e.message)));
}
window.addEventListener('hashchange',()=>{if(data)render()});window.addEventListener('online',()=>{if(data)render()});window.addEventListener('offline',()=>{if(data)render()});
try{await db.initialize();if(db.live)month=today.slice(0,7);if(db.live&&!db.session){$('#app').innerHTML='<div class="login"><div class="brand"><i>D</i> DUCKY</div><h1>ทุกงานฟาร์ม ในที่เดียว</h1><p>เข้าสู่ระบบเพื่อเลือกพื้นที่ทำงานตามสิทธิ์</p><button class="primary" id="login">เข้าสู่ระบบด้วย Google</button></div>';on('#login','click',()=>db.login().catch(e=>toast(e.message)));}else if(db.live&&!db.profile?.approved){$('#app').innerHTML='<div class="login"><h1>รออนุมัติบัญชี</h1><p>บัญชียืนยันแล้ว แต่ยังไม่ได้รับสิทธิ์ใช้งาน</p><button id="logout">ออกจากระบบ</button></div>';on('#logout','click',()=>db.logout());}else{await reload();}}
catch(err){$('#app').innerHTML=`<div class="login"><h1>โหลดข้อมูลไม่สำเร็จ</h1><p>${esc(err.message)}</p><button onclick="location.reload()">ลองใหม่</button></div>`}
if('serviceWorker'in navigator&&import.meta.env.PROD)navigator.serviceWorker.register('./sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)toast('มีเวอร์ชันใหม่ ปิดและเปิดแอปเมื่อบันทึกงานเสร็จ')})})}).catch(()=>toast('ติดตั้ง offline shell ไม่สำเร็จ'));
