export const money=n=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:0}).format(Number(n)||0);
export function dateUTC(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))throw Error('วันที่ไม่ถูกต้อง');const d=new Date(s+'T00:00:00Z');if(!Number.isFinite(+d)||d.toISOString().slice(0,10)!==s)throw Error('วันที่ไม่ถูกต้อง');return d}
export function addDays(s,n){if(!Number.isInteger(+n)||+n<0||+n>3650)throw Error('วันเครดิตต้องอยู่ระหว่าง 0–3650');const d=dateUTC(s);d.setUTCDate(d.getUTCDate()+Number(n));return d.toISOString().slice(0,10)}
export const daysBetween=(a,b)=>Math.round((dateUTC(b)-dateUTC(a))/86400000);
export const thaiDate=s=>dateUTC(s).toLocaleDateString('th-TH',{day:'numeric',month:'short',year:'2-digit',timeZone:'UTC'});
export function compareBatches(batches,rows){if(batches.length<2)throw Error('เลือกอย่างน้อย 2 ล็อต');if(new Set(batches.map(b=>b.species_id)).size!==1)throw Error('เปรียบเทียบได้เฉพาะชนิดเดียวกัน');return batches.map(b=>{const r=rows.filter(x=>x.batch_id===b.id&&x.data_complete!==false);const paired=r.filter(x=>Number.isFinite(x.live_count)&&x.live_count>0);const live=paired.reduce((s,x)=>s+x.live_count,0);const eggs=r.reduce((s,x)=>s+x.total,0);return {...b,days:r.length,eggs,rate_days:paired.length,rate:live?paired.reduce((s,x)=>s+x.total,0)/live*100:null}})}
// Forecast only. No writes to actual ledger, no automatic transfers across batches.
export function forecast(p){for(const k of ['count','days','layStart','layRate','eggPrice','feedKg','feedPrice','dailyExpense','investment','salvage','target'])if(!Number.isFinite(+p[k])||+p[k]<0)throw Error('ปัจจัยต้องเป็นตัวเลขตั้งแต่ศูนย์ขึ้นไป');if(!Number.isInteger(p.days)||!Number.isInteger(p.count)||!Number.isInteger(p.layStart)||p.days<1||p.days>3650||p.layRate>100)throw Error('ตรวจระยะเลี้ยงและอัตราไข่');let net=-p.investment,breakEven=null;const rows=[];for(let day=1;day<=p.days;day++){const revenue=day>=p.layStart?p.count*p.layRate/100*p.eggPrice:0;const cost=p.count*p.feedKg*p.feedPrice+p.dailyExpense;net+=revenue-cost;if(breakEven===null&&net>=0)breakEven=day;if(day%30===0||day===+p.days)rows.push({day,net});}return {rows,operatingNet:net,finalNet:net+p.salvage,breakEven,gap:p.target-(net+p.salvage)}}
export function paymentPlan(income,reserve,bills){if(income<0||reserve<0)throw Error('ยอดต้องไม่ติดลบ');let available=Math.max(0,income-reserve);const payments=[];for(const b of [...bills].sort((a,b)=>a.order_date.localeCompare(b.order_date)||a.id.localeCompare(b.id))){const amount=Math.min(available,Math.max(0,b.outstanding));if(amount){payments.push({...b,amount});available-=amount;}}return {payments,shortfall:Math.max(0,reserve-income),unallocated:available}}
export function newEgg(data){if(!Number.isInteger(data.total)||!Number.isInteger(data.broken)||data.total<0||data.broken<0||data.broken>data.total)throw Error('ตรวจจำนวนไข่');dateUTC(data.log_date);return data}
