import {renderFeedCalendar,paymentState} from './feed-calendar.js';
import {money,thaiDate,addDays,daysBetween} from './domain.js';
import {icon} from './ui.js';
export const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const quantity=n=>Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:3});
const unitPrice=n=>Number(n||0).toLocaleString('th-TH',{maximumFractionDigits:4});
const f=(label,name,value='',type='text',attrs='')=>`<label>${label}<input name="${name}" value="${esc(value)}" type="${type}" ${attrs}></label>`;
const num=(label,name,value='',step='.01',min='0')=>f(label,name,value,'number',`required min="${min}" step="${step}"`);
const select=(label,name,options)=>`<label>${label}<select name="${name}" required>${options}</select></label>`;
const option=(v,t)=>`<option value="${esc(v)}">${esc(t)}</option>`;
const note=()=>'<label>หมายเหตุ<textarea name="note" rows="2" maxlength="1000"></textarea></label>';
const button=(text,action,ico='add')=>`<button type="button" class="action-button" data-act="${action}">${icon(ico)}<span>${text}</span></button>`;
const form=(name,body,label='บันทึก')=>`<form id="${name}">${body}<p class="form-error" role="alert"></p><button class="primary action-button" type="submit">${icon('save')}<span>${label}</span></button></form>`;
const section=(title,body)=>`<section class="section"><header><h2>${title}</h2></header>${body}</section>`;
const table=(headers,rows)=>`<div class="table-scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">ยังไม่มีรายการ</td></tr>`}</tbody></table></div>`;
const td=xs=>'<tr>'+xs.map(x=>'<td>'+x+'</td>').join('')+'</tr>';
const errors={UNCERTAIN_PENDING:'ยังมีรายการที่ไม่ทราบผล กรุณาปิดหน้าต่าง โหลดเว็บใหม่ แล้วใช้ปุ่มตรวจคำขอเดิมก่อนทำรายการใหม่',NO_ACCESS:'บัญชีนี้ไม่มีสิทธิ์ทำรายการ',NO_BATCH_ACCESS:'ไม่มีสิทธิ์เขียนข้อมูลในล็อตสัตว์ที่เลือก',VERSION_CONFLICT:'รายการถูกแก้ไขแล้ว กรุณาปิดหน้าต่างและโหลดข้อมูลใหม่',LINKED_ORDER_LOCKED:'บิลมีการจ่าย เคลม หรือแบ่งอาหารแล้ว แก้ได้เฉพาะเครดิต ผู้ขาย และข้อมูลประกอบ เพื่อรักษาประวัติ',INSUFFICIENT_CENTRAL_STOCK:'อาหารคงเหลือส่วนกลางไม่พอ กรุณาโหลดข้อมูลล่าสุด',INSUFFICIENT_BATCH_CASH:'เงินของล็อตนี้ไม่พอ หรือทำให้ยอดย้อนหลังติดลบ',PAYMENT_PREVIEW_CHANGED:'ยอดหรือรายการเปลี่ยนไป กรุณาดูตัวอย่างการจ่ายใหม่ก่อนยืนยัน',NO_PAYABLE_ORDERS:'ไม่มีบิลค้างจ่ายที่จ่ายได้ในวันที่เลือก',OPENING_MUST_BE_FIRST:'ยอดยกมาต้องเป็นรายการแรกของล็อต หากมีรายการแล้วให้บันทึกรับเงินแทน',CLAIM_EXCEEDS_INVOICE_VALUE:'มูลค่าคืนเกินมูลค่าบิลสุทธิ กรุณาตรวจราคาคืน',PAYMENT_DATE_BEFORE_ACTIVITY:'วันที่จ่ายอยู่ก่อนประวัติจ่ายหรือเคลมล่าสุดของบิล',INVALID_DATE:'ตรวจวันที่ ต้องไม่ก่อนต้นทางและไม่เป็นวันในอนาคต',SPECIES_LOCKED:'ไม่สามารถเปลี่ยนชนิดสัตว์ของล็อตเดิมได้',OFFLINE:'ออฟไลน์ กรุณาเชื่อมต่อก่อนบันทึก',IDEMPOTENCY_CONFLICT:'คำขอนี้เคยใช้กับข้อมูลอื่นแล้ว กรุณาโหลดข้อมูลใหม่'};
function message(e){const m=e.message||String(e);return Object.entries(errors).find(([k])=>m.includes(k))?.[1]||m}
function values(el){return Object.fromEntries(new FormData(el))}
function normalize(v,keys){for(const k of keys)v[k]=v[k]===''?null:Number(v[k]);return v}
let selected='',month='',filter='pending',showHidden=false,search='',generation=0;
function dialog(title,body){document.querySelector('#workDialog')?.remove();const d=document.createElement('dialog');d.id='workDialog';d.className='work-dialog';d.innerHTML=`<header><h2>${title}</h2><button type="button" class="icon-button" aria-label="ปิดหน้าต่าง">${icon('close')}</button></header>${body}`;document.body.append(d);d.querySelector('header button').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d}
async function saveForm(event,ctx,fn,d){event.preventDefault();const form=event.target;if(form.dataset.busy)return;form.dataset.busy='1';const buttons=[...form.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);const err=form.querySelector('.form-error');err.textContent='';try{await fn(values(form));d?.close();try{await ctx.reload();ctx.toast('บันทึกสำเร็จ')}catch(e){ctx.toast('บันทึกแล้ว แต่โหลดข้อมูลล่าสุดไม่ได้ กรุณารีโหลดเว็บ')}}catch(e){err.textContent=message(e)}finally{delete form.dataset.busy;buttons.forEach(b=>b.disabled=false)}}
function editOrder(ctx,o){const creating=!o,oid=o?.id||crypto.randomUUID();o||={feed_name:'',order_date:ctx.today,credit_days:25,quantity:200,unit:'กระสอบ',unit_price:800,total:160000};const d=dialog(creating?'เพิ่มบิลอาหาร':'แก้ไขบิลอาหาร',form('billEdit',`${f('ผู้ขาย','supplier_name',o.supplier_name)}${f('ชื่ออาหาร','feed_name',o.feed_name,'text','required maxlength="200"')}<div class="form-grid">${f('วันที่สั่ง','order_date',o.order_date,'date','required')}${num('เครดิต (วัน)','credit_days',o.credit_days,'1')}${num('จำนวน','quantity',o.quantity,'.001','.001')}${f('หน่วย','unit',o.unit,'text','required')}${num('ราคาต่อหน่วย','unit_price',o.unit_price,'.0001')}${f('กก./หน่วย (ถ้าทราบ)','kg_per_unit',o.kg_per_unit,'number','min="0.0001" step=".0001"')}${num('ยอดบิลรวม','total',o.total)}</div><button type="button" id="calculateTotal">คำนวณจำนวน × ราคา</button><output id="editDue"></output>${f('รหัสล็อตผู้ผลิต','manufacturer_lot',o.manufacturer_lot)}${f('สูตรอาหาร','formula',o.formula)}${note()}${creating?'':'<p class="muted">ถ้ามีประวัติจ่าย/เคลม/แบ่งแล้ว ระบบจะคงจำนวนและราคาเดิมไว้</p>'}`));const el=d.querySelector('form');el.elements.note.value=o.note||'';const preview=()=>{try{d.querySelector('#editDue').textContent='ครบดีล '+thaiDate(addDays(el.elements.order_date.value,+el.elements.credit_days.value))}catch{}};el.oninput=preview;preview();d.querySelector('#calculateTotal').onclick=()=>{el.elements.total.value=(+el.elements.quantity.value*+el.elements.unit_price.value).toFixed(2)};el.onsubmit=e=>saveForm(e,ctx,v=>ctx.db.saveOrder({...normalize(v,['credit_days','quantity','unit_price','total','kg_per_unit']),id:oid,version:creating?0:o.version}),d)}
function payment(ctx,o){const funds=ctx.data.context.funds.filter(x=>x.can_write);if(!funds.length)return ctx.toast('ต้องมีล็อตสัตว์และสิทธิ์การเงินก่อน ไปที่หน้าสัตว์และฟาร์ม');const d=dialog(o?'จ่ายบิล '+thaiDate(o.order_date):'จ่ายยอดรวม • บิลเก่าสุดก่อน',form('paymentForm',`${select('ใช้เงินของล็อตสัตว์', 'batch_id',funds.map(b=>option(b.id,`${b.name} · เงินปัจจุบัน ${money(b.balance)} บาท`)).join(''))}<p class="callout">หักเงินจากล็อตที่เลือกเท่านั้น แม้ยังไม่ได้แบ่งอาหารเข้าเล้า กรุณาเลือกเจ้าของเงินให้ถูกต้อง</p><div class="form-grid">${num('ยอดที่ต้องการจ่าย','amount',o?.outstanding||'')}${f('วันที่จ่าย','payment_date',ctx.today,'date',`required max="${ctx.today}"`)}</div>${select('วิธีจ่าย','payment_method',option('transfer','โอนเงิน')+option('cash','เงินสด')+option('other','อื่น ๆ'))}${note()}`,'ดูตัวอย่างการจ่าย')+'<div id="paymentPreview" aria-live="polite"></div>');const el=d.querySelector('form'),out=d.querySelector('#paymentPreview');el.oninput=()=>{out.innerHTML=''};
 el.onsubmit=async e=>{e.preventDefault();const btn=el.querySelector('button[type=submit]');btn.disabled=true;out.innerHTML='';el.querySelector('.form-error').textContent='';try{const p={...normalize(values(el),['amount']),order_id:o?.id||null};const snapshot=JSON.stringify(values(el));const plan=await ctx.db.paymentPreview(p);if(snapshot!==JSON.stringify(values(el)))return;out.innerHTML=`<h3>ตรวจรายการก่อนยืนยัน</h3>${table(['บิลวันที่','ค้างก่อนจ่าย','จ่ายครั้งนี้','ค้างหลังจ่าย'],plan.rows.map(r=>td([thaiDate(r.order_date),money(r.before),money(r.amount),money(r.after)])))}<p>หักเงินจริง <strong>${money(plan.applied)}</strong> บาท · เงินที่ใช้ได้ในวันที่เลือก ${money(plan.available_cash)} บาท</p>${plan.unapplied>0?`<p>ยอดที่เกินหนี้ ${money(plan.unapplied)} บาท จะไม่ถูกหัก</p>`:''}${plan.can_pay?'<button type="button" class="primary" id="confirmPayment">ยืนยันบันทึกการจ่ายเงิน</button>':'<p class="form-error">เงินของล็อตที่เลือกไม่พอ กรุณาบันทึกรับเงินจริงที่หน้าแผนการเงินก่อน</p>'}<p class="form-error" role="alert"></p>`;const confirm=out.querySelector('#confirmPayment');if(confirm)confirm.onclick=async()=>{confirm.disabled=true;try{await ctx.db.write('feed_pay',{p_data:p,p_expected:plan.fingerprint});d.close();try{await ctx.reload();ctx.toast('บันทึกการจ่ายแล้ว')}catch{ctx.toast('บันทึกแล้ว กรุณารีโหลดเพื่อดูยอดล่าสุด')}}catch(err){out.querySelector('.form-error').textContent=message(err);confirm.disabled=false}};}catch(err){el.querySelector('.form-error').textContent=message(err)}finally{btn.disabled=false}};
}
function sourceOptions(sources){return sources.filter(s=>s.available>0).map(s=>option(s.source_claim_id||'original',`${s.source_claim_id?'รับจากเคลม':'ล็อตเดิม'} · ${s.feed_name} · เหลือ ${s.available} ${s.unit} · ${unitPrice(s.unit_price)} บาท`)).join('')}
function allocation(ctx,o,detail){const available=detail.sources.filter(s=>s.available>0);if(!available.length)return ctx.toast('ไม่มีอาหารส่วนกลางคงเหลือ');const batches=ctx.data.batches.filter(b=>ctx.data.context.farm_write_ids.includes(b.id)&&b.status!=='closed');const d=dialog('แบ่งอาหารเข้าเล้า / ปลายทาง',form('allocateForm',`${select('อาหารต้นทาง','source_claim_id',sourceOptions(available))}${select('ประเภทปลายทาง','destination_type',option('batch','ล็อตสัตว์ในระบบ')+option('external','เล้า / ปลายทางภายนอก'))}<div id="batchDestination">${select('ล็อตสัตว์ / เล้า','batch_id',batches.map(b=>option(b.id,b.name)).join(''))}</div><div id="externalDestination" hidden>${f('ชื่อปลายทางภายนอก','external_name')}</div><div class="form-grid">${num('จำนวนแบ่ง','quantity',1,'.001','.001')}${num('ราคาต่อหน่วยเข้าล็อตสัตว์','unit_price',available[0].unit_price,'.0001')}${f('วันที่แบ่ง','allocation_date',ctx.today,'date',`required max="${ctx.today}"`)}</div>${note()}<p class="muted">สร้างรายการอาหารรับเข้าแยกตามต้นทางและราคา บันทึกเข้าสต็อกของล็อตที่เลือก</p>`));const el=d.querySelector('form');const dest=()=>{const external=el.elements.destination_type.value==='external';d.querySelector('#batchDestination').hidden=external;d.querySelector('#externalDestination').hidden=!external;el.elements.batch_id.required=!external;el.elements.external_name.required=external};el.elements.destination_type.onchange=dest;if(!batches.length)el.elements.destination_type.value='external';dest();el.elements.source_claim_id.onchange=()=>{el.elements.unit_price.value=available.find(s=>(s.source_claim_id||'original')===el.elements.source_claim_id.value).unit_price};el.onsubmit=e=>saveForm(e,ctx,v=>ctx.db.write('feed_allocate',{p_data:{...normalize(v,['quantity','unit_price']),order_id:o.id,source_claim_id:v.source_claim_id==='original'?null:v.source_claim_id,batch_id:v.destination_type==='batch'?v.batch_id:null,external_name:v.destination_type==='external'?v.external_name:null}}),d)}
function claim(ctx,o,detail){const ss=detail.sources.filter(s=>s.available>0);if(!ss.length)return ctx.toast('ไม่มีอาหารส่วนกลางให้คืน/เคลม');const d=dialog('เคลม / คืนอาหาร',form('claimForm',`${select('ล็อตอาหารที่ส่งคืน','source_claim_id',sourceOptions(ss))}${f('วันที่เคลม','claim_date',ctx.today,'date',`required max="${ctx.today}"`)}<div class="form-grid">${num('จำนวนส่งคืน','return_qty',1,'.001')}${num('จำนวนรับทดแทน','replacement_qty',1,'.001')}</div>${select('ราคาที่รับทดแทน','price_mode',option('same','ราคาเดิมของอาหารที่ส่งคืน')+option('new','ราคาใหม่'))}${f('ชื่ออาหารรับทดแทน','replacement_feed_name',ss[0].feed_name,'text','required')}${num('ราคาต่อหน่วยรับทดแทน','replacement_unit_price',ss[0].unit_price,'.0001')}${f('สาเหตุ','reason','','text','required maxlength="500"')}${note()}<output id="claimPreview"></output><p class="muted">ตัดจำนวนส่งคืนออกจากสต็อกส่วนกลาง และแยกอาหารรับทดแทนเป็นล็อตย่อยใหม่</p>`));const el=d.querySelector('form');const update=()=>{const src=ss.find(s=>(s.source_claim_id||'original')===el.elements.source_claim_id.value);const same=el.elements.price_mode.value==='same';el.elements.replacement_unit_price.readOnly=same;if(same)el.elements.replacement_unit_price.value=src.unit_price;const ret=+el.elements.return_qty.value*src.unit_price,rep=+el.elements.replacement_qty.value*+el.elements.replacement_unit_price.value;d.querySelector('#claimPreview').textContent=`มูลค่าคืน ${money(ret)} · รับทดแทน ${money(rep)} · ส่วนต่างบิล ${money(rep-ret)} บาท`;el.elements.replacement_feed_name.required=+el.elements.replacement_qty.value>0};el.oninput=update;el.onchange=update;update();el.onsubmit=e=>saveForm(e,ctx,v=>{delete v.price_mode;return ctx.db.write('feed_claim',{p_data:{...normalize(v,['return_qty','replacement_qty','replacement_unit_price']),order_id:o.id,source_claim_id:v.source_claim_id==='original'?null:v.source_claim_id}})},d)}
export function mountFeed(root,ctx){const token=++generation;const {data,today}=ctx;const writable=data.context.feed_write;const visible=data.orders.filter(o=>showHidden||o.is_visible!==false);let rows=visible.filter(o=>filter==='all'||(filter==='pending'?o.outstanding>0:o.outstanding===0));if(search)rows=rows.filter(o=>(o.feed_name+' '+o.supplier_name+' '+o.order_date).toLowerCase().includes(search.toLowerCase()));rows.sort((a,b)=>a.order_date.localeCompare(b.order_date));if(!visible.some(o=>o.id===selected))selected=rows[0]?.id||visible[0]?.id||'';const o=data.orders.find(o=>o.id===selected);month||=o?.order_date.slice(0,7)||today.slice(0,7);
 const controls=`<div class="feed-actions">${writable?button('เพิ่มบิล','new')+button('จ่ายยอดรวม','bulk','finance'):''}${button('โหลดล่าสุด','refresh','reset')}</div><div class="filter-tabs" role="group" aria-label="สถานะบิล">${[['pending','ค้างจ่าย'],['all','ทั้งหมด'],['paid','เคลียร์แล้ว']].map(([v,t])=>`<button data-filter="${v}" aria-pressed="${filter===v}">${t}</button>`).join('')}</div><label>ค้นชื่ออาหาร ผู้ขาย หรือวันที่สั่ง<input id="feedSearch" value="${esc(search)}" placeholder="ค้นหาแล้วกด Enter"></label><label class="check-label"><input type="checkbox" id="showHidden" ${showHidden?'checked':''}>แสดงล็อตที่ซ่อนไว้ด้วย</label>`;
 const stats=`<div class="stats"><div class="stat"><span>บิลที่แสดง</span><strong>${visible.length}</strong></div><div class="stat"><span>ยอดค้างรวม</span><strong>${money(visible.reduce((s,o)=>s+o.outstanding,0))}</strong></div><div class="stat"><span>เครดิตคงค้างกับผู้ขาย</span><strong>${money(visible.reduce((s,o)=>s+(o.supplier_credit||0),0))}</strong></div></div>`;
 root.innerHTML=`<div class="workspace wide-left"><div class="zone">${section('บิลอาหารกลาง',controls+stats)}${section('ปฏิทินวันสั่งถึงครบดีล',renderFeedCalendar({month,orders:rows,today,selected}))}${section('รายการล็อต',rows.map(x=>`<button class="feed-lot ${x.id===selected?'active':''}" data-lot="${esc(x.id)}"><span><strong>${esc(x.feed_name)}</strong><small>${esc(x.supplier_name)} · สั่ง ${thaiDate(x.order_date)} → ${thaiDate(addDays(x.order_date,x.credit_days))}</small></span><span>ค้าง ${money(x.outstanding)}<small>${paymentState(x,today).label}${x.is_visible===false?' · ซ่อนไว้':''}</small></span></button>`).join('')||'<p>ไม่มีบิลในตัวกรองนี้</p>')}</div><div class="zone">${section('รายละเอียดและทำรายการ',o?`<h3>${esc(o.feed_name)}</h3><p>สั่ง ${thaiDate(o.order_date)} · ครบดีล ${thaiDate(addDays(o.order_date,o.credit_days))}</p><div class="stats"><div class="stat"><span>ยอดสุทธิหลังเคลม</span><strong>${money(o.net_total??o.total)}</strong></div><div class="stat"><span>จ่ายแล้ว</span><strong>${money(o.paid_total)}</strong></div><div class="stat"><span>ยอดค้าง</span><strong>${money(o.outstanding)}</strong></div></div>${o.supplier_credit>0?`<p class="callout">มีเครดิต/ยอดต้องคืนจากผู้ขาย ${money(o.supplier_credit)} บาท ยังไม่ใช่เงินรับเข้าล็อตสัตว์</p>`:''}<p>ส่วนกลางเหลือ ${quantity(o.available_quantity)} ${esc(o.unit)} · แบ่งแล้ว ${quantity(o.allocated_quantity)} ${esc(o.unit)}</p><div class="feed-actions">${writable?button('แก้บิล','edit','edit')+button('จ่ายบิลนี้','pay','finance')+button(o.is_visible===false?'แสดงล็อต':'ซ่อนล็อต','visibility','more'):''}</div><div id="feedDetail" aria-live="polite">กำลังโหลดประวัติ…</div>`:'<p>เพิ่มบิลอาหารเพื่อเริ่มใช้งาน</p>')}</div></div>`;
 root.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;mountFeed(root,ctx)});root.querySelector('#feedSearch').onchange=e=>{search=e.target.value;mountFeed(root,ctx)};root.querySelector('#showHidden').onchange=e=>{showHidden=e.target.checked;mountFeed(root,ctx)};
 root.querySelectorAll('[data-lot],[data-order]').forEach(b=>b.onclick=()=>{selected=b.dataset.lot||b.dataset.order;mountFeed(root,ctx);if(innerWidth<760)root.querySelector('.zone:last-child').scrollIntoView({block:'start'})});
 for(const [id,delta]of [['prevMonth',-1],['nextMonth',1]])root.querySelector('#'+id).onclick=()=>{const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+delta);month=d.toISOString().slice(0,7);mountFeed(root,ctx)};
 root.querySelector('#lotMonth').onclick=()=>{month=o?.order_date.slice(0,7)||today.slice(0,7);mountFeed(root,ctx)};root.querySelector('#currentMonth').onclick=()=>{month=today.slice(0,7);mountFeed(root,ctx)};
 root.querySelectorAll('[data-act]').forEach(b=>b.onclick=async()=>{try{switch(b.dataset.act){case'new':editOrder(ctx);break;case'edit':editOrder(ctx,o);break;case'pay':payment(ctx,o);break;case'bulk':payment(ctx);break;case'refresh':await ctx.reload();break;case'visibility':await ctx.db.visibility(o,o.is_visible===false);await ctx.reload();break}}catch(e){ctx.toast(message(e))}});
 if(o&&writable){
  const drag=document.createElement('button');drag.type='button';drag.className='drag-end desktop-drag';drag.draggable=true;drag.textContent='ลากวันครบดีล → '+thaiDate(addDays(o.order_date,o.credit_days));drag.title='ลากปุ่มนี้ไปวางบนวันที่ในปฏิทิน หรือใช้แก้บิลบนมือถือ';root.querySelector('#feedDetail').before(drag);drag.ondragstart=e=>e.dataTransfer.setData('text/plain',o.id);
  root.querySelectorAll('[data-date]').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=async e=>{e.preventDefault();if(e.dataTransfer.getData('text/plain')!==o.id)return;const n=daysBetween(o.order_date,el.dataset.date);if(n<0||n>3650)return ctx.toast('วันครบดีลต้องไม่ก่อนวันสั่ง และเครดิตไม่เกิน 3,650 วัน');if(!confirm('เปลี่ยนวันครบดีลเป็น '+thaiDate(el.dataset.date)+'?'))return;try{await ctx.db.saveOrder({...o,credit_days:n});await ctx.reload();ctx.toast('แก้วันครบดีลแล้ว')}catch(err){ctx.toast(message(err))}}});
 }
 if(o)ctx.db.feedDetail(o.id).then(detail=>{if(token!==generation||!root.isConnected)return;const target=root.querySelector('#feedDetail');target.innerHTML=`<div class="feed-actions">${writable?button('แบ่งเข้าเล้า','allocate','farm')+button('เคลม / คืน','claim','reset'):''}</div><h3>อาหารส่วนกลางแยกต้นทาง</h3>${table(['ต้นทาง','อาหาร','คงเหลือ','ราคา/หน่วย'],detail.sources.map(s=>td([s.source_claim_id?'รับจากเคลม':'ล็อตเดิม',esc(s.feed_name),quantity(s.available)+' '+esc(s.unit),unitPrice(s.unit_price)])))}<details open><summary>ประวัติจ่าย (${detail.payments.length})</summary>${table(['วันที่','เงินของล็อต','จ่าย','วิธี / หมายเหตุ'],detail.payments.map(p=>td([thaiDate(p.payment_date),esc(p.batch_name),money(p.amount),esc(p.payment_method)+' '+esc(p.note)])))}</details><details><summary>ประวัติเคลม (${detail.claims.length})</summary>${table(['วันที่','คืน','รับทดแทน','ราคาทดแทน','ส่วนต่าง','สาเหตุ'],detail.claims.map(c=>td([thaiDate(c.claim_date),quantity(c.return_qty),esc(c.replacement_feed_name)+' '+quantity(c.replacement_qty),unitPrice(c.replacement_unit_price),money(c.replacement_value-c.return_value),esc(c.reason)])))}</details><details><summary>ประวัติแบ่งอาหาร (${detail.allocations.length})</summary>${table(['วันที่','ปลายทาง','อาหาร','จำนวน','ต้นทุน'],detail.allocations.map(a=>td([thaiDate(a.allocation_date),esc(a.batch_name||a.external_name),esc(a.feed_name),quantity(a.quantity)+' '+esc(a.unit),money(a.assigned_cost)])))}</details>`;target.querySelector('[data-act=allocate]')?.addEventListener('click',()=>allocation(ctx,o,detail));target.querySelector('[data-act=claim]')?.addEventListener('click',()=>claim(ctx,o,detail));}).catch(e=>{if(token===generation&&root.isConnected)root.querySelector('#feedDetail').textContent=message(e)});
}

export function mountBatchTools(root,ctx,batchId){
 if(!ctx.data.context.is_admin){root.innerHTML='<p class="muted">ผู้ดูแลระบบเป็นผู้สร้างและแก้ข้อมูลตั้งต้นของล็อตสัตว์</p>';return}
 root.innerHTML=`<div class="feed-actions">${button('เพิ่มล็อตสัตว์','newBatch','add')}${batchId?button('แก้ข้อมูลล็อตนี้','editBatch','edit'):''}</div>`;
 const edit=b=>{const creating=!b,uid=b?.id||crypto.randomUUID();b||={name:'',species_id:'duck',start_date:ctx.today,initial_qty:0,status:'active'};const d=dialog(creating?'เพิ่มล็อตสัตว์':'แก้ข้อมูลล็อตสัตว์',form('batchEdit',`${f('ชื่อล็อต / เล้า','name',b.name,'text','required maxlength="200"')}${select('ชนิดสัตว์','species_id',option('duck','เป็ด')+option('fish','ปลา'))}<div class="form-grid">${f('วันเริ่มเลี้ยง','start_date',b.start_date,'date','required')}${num('จำนวนเริ่มต้น','initial_qty',b.initial_qty,'1')}${f('วันเกิด (ถ้าทราบ)','birth_date',b.birth_date,'date')}${f('อายุวันเริ่มเลี้ยง (วัน)','age_at_start_days',b.age_at_start_days,'number','min="0" step="1"')}${f('ต้นทุนซื้อสัตว์ (บาท)','purchase_cost',b.purchase_cost,'number','min="0" step=".01"')}${select('สถานะ','status',option('active','กำลังเลี้ยง')+option('closed','ปิดล็อต'))}${f('วันปิดล็อต','end_date',b.end_date,'date')}</div><p class="muted">ต้นทุนซื้อสัตว์เป็นข้อมูลตั้งต้น ไม่หักเงินอัตโนมัติ กรุณาบันทึกเงินที่จ่ายจริงในหน้าการเงินแยกล็อต</p>`));const el=d.querySelector('form');el.elements.species_id.value=b.species_id;el.elements.status.value=b.status||'active';if(!creating){el.elements.species_id.setAttribute('aria-readonly','true');el.elements.species_id.onchange=()=>{el.elements.species_id.value=b.species_id}}el.onsubmit=e=>saveForm(e,ctx,v=>ctx.db.write('batch_save',{p_data:{...normalize(v,['initial_qty','age_at_start_days','purchase_cost']),id:uid,version:creating?0:(b.version||1)}}),d)};
 root.querySelector('[data-act=newBatch]').onclick=()=>edit();root.querySelector('[data-act=editBatch]')?.addEventListener('click',()=>edit(ctx.data.batches.find(b=>b.id===batchId)));
}
let cashBatch='';
const cashNames={opening:'ยอดยกมา',receipt:'รับเงิน',expense:'ค่าใช้จ่าย',withdrawal:'เบิกเงิน',savings_transfer:'แยกเก็บเงิน',feed_payment:'จ่ายค่าอาหาร'};
export function mountCash(root,ctx){const funds=ctx.data.context.funds;if(!funds.some(b=>b.id===cashBatch))cashBatch=funds[0]?.id||'';const fund=funds.find(b=>b.id===cashBatch),rows=(ctx.data.cash||[]).filter(c=>c.batch_id===cashBatch).sort((a,b)=>b.cash_date.localeCompare(a.cash_date));
 root.innerHTML=section('เงินสดแยกล็อต',fund?`${select('ล็อตเจ้าของเงิน','cash_batch',funds.map(b=>option(b.id,b.name)).join(''))}<div class="stats"><div class="stat"><span>เงินพร้อมใช้ปัจจุบัน</span><strong>${money(fund.balance)}</strong><small>บาท · ${esc(fund.name)}</small></div><div class="stat"><span>แยกเก็บสะสม</span><strong>${money(-rows.filter(c=>c.kind==='savings_transfer').reduce((n,c)=>n+Number(c.amount),0))}</strong><small>เงินที่นำออกจากกองใช้งาน ไม่ใช่กำไร</small></div></div>${fund.can_write?button('บันทึกรับ / จ่าย / เบิก / เก็บเงิน','cash','finance'):''}<p class="muted">บันทึกยอดยกมาตามเงินจริงครั้งแรก จากนั้นบันทึกรายรับและรายจ่ายของล็อตนี้ การจ่ายบิลอาหารจะหักเงินให้โดยอัตโนมัติ ห้ามบันทึกค่าอาหารซ้ำเป็นค่าใช้จ่าย</p>${table(['วันที่','ประเภท','จำนวนเงิน','หมายเหตุ'],rows.map(c=>td([thaiDate(c.cash_date),esc(cashNames[c.kind]||c.kind),money(c.amount),esc(c.note)])))}`:'<p>ยังไม่มีล็อตที่เข้าถึงเงินได้ กรุณาสร้างล็อตสัตว์ก่อน หรือให้ผู้ดูแลเพิ่มสิทธิ์การเงิน</p>');if(!fund)return;
 const selector=root.querySelector('select');selector.value=cashBatch;selector.onchange=()=>{cashBatch=selector.value;mountCash(root,ctx)};
 root.querySelector('[data-act=cash]')?.addEventListener('click',()=>{const d=dialog('บันทึกเงิน • '+esc(fund.name),form('cashForm',`${select('ประเภท','kind',Object.entries(cashNames).filter(([k])=>k!=='feed_payment'&&(k!=='opening'||!rows.length)).map(([k,v])=>option(k,v)).join(''))}<div class="form-grid">${f('วันที่','cash_date',ctx.today,'date',`required max="${ctx.today}"`)}${num('จำนวนเงิน (ใส่ค่าบวก)','amount','', '.01','.01')}</div>${note()}<p class="callout">แยกเก็บเงิน = ย้ายออกจากเงินพร้อมใช้ของล็อตนี้ ระบบยังไม่จัดการบัญชีธนาคารหรือการคืนเงินเก็บอัตโนมัติ</p>`));const el=d.querySelector('form');el.elements.note.required=true;el.onsubmit=e=>saveForm(e,ctx,v=>ctx.db.write('cash_record',{p_data:{...normalize(v,['amount']),batch_id:fund.id}}),d)});
}
