// Demo-only ledger. Production writes always run PostgreSQL RPC transactions.
export const round=(n,d=2)=>Number(Number(n).toFixed(d));
const id=()=>crypto.randomUUID();
export function prepareDemo(s){for(const k of ['claims','allocations','payments','cash'])s[k]??=[];for(const o of s.orders){o.unit_price??=round(o.total/o.quantity,4);o.is_visible??=true;o.supplier_name??='';}return s}
export function totals(s,o){const cs=s.claims.filter(c=>c.order_id===o.id),as=s.allocations.filter(a=>a.order_id===o.id);const net=round(o.total+cs.reduce((n,c)=>n+c.replacement_value-c.return_value,0)),paid=round(Number(o.paid_total||0)+s.payments.filter(p=>p.order_id===o.id).reduce((n,p)=>n+p.amount,0));return{net_total:net,paid_total:paid,outstanding:Math.max(0,round(net-paid)),supplier_credit:Math.max(0,round(paid-net)),available_quantity:round(o.quantity+cs.reduce((n,c)=>n+c.replacement_qty-c.return_qty,0)-as.reduce((n,a)=>n+a.quantity,0),3),allocated_quantity:as.reduce((n,a)=>n+a.quantity,0)}}
export function source(s,oid,sid=null){const o=s.orders.find(x=>x.id===oid),c=sid?s.claims.find(x=>x.id===sid&&x.order_id===oid):null;if(!o||(sid&&!c))throw Error('SOURCE_NOT_FOUND');return{source_claim_id:sid,feed_name:c?c.replacement_feed_name:o.feed_name,unit:o.unit,unit_price:c?c.replacement_unit_price:o.unit_price,available_from:c?c.claim_date:o.order_date,available:round((c?c.replacement_qty:o.quantity)-s.claims.filter(x=>x.order_id===oid&&(x.source_claim_id||null)===sid).reduce((n,x)=>n+x.return_qty,0)-s.allocations.filter(x=>x.order_id===oid&&(x.source_claim_id||null)===sid).reduce((n,x)=>n+x.quantity,0),3)}}
export function detail(s,oid){const addName=x=>({...x,batch_name:s.batches.find(b=>b.id===x.batch_id)?.name});return{sources:[source(s,oid),...s.claims.filter(c=>c.order_id===oid&&c.replacement_qty>0).map(c=>source(s,oid,c.id))],claims:s.claims.filter(c=>c.order_id===oid),allocations:s.allocations.filter(a=>a.order_id===oid).map(addName),payments:s.payments.filter(p=>p.order_id===oid).map(addName)}}
export function availableCash(s,b,date){const rows=s.cash.filter(c=>c.batch_id===b),dates=[...new Set([date,...rows.filter(c=>c.cash_date>date).map(c=>c.cash_date)])];return Math.min(...dates.map(d=>round(rows.filter(c=>c.cash_date<=d).reduce((n,c)=>n+c.amount,0))))}
export function previewPayment(s,p){if(!(p.amount>0))throw Error('INVALID_PAYMENT');let left=p.amount;const rows=[];for(const o of [...s.orders].filter(o=>p.order_id?o.id===p.order_id:o.is_visible).sort((a,b)=>a.order_date.localeCompare(b.order_date)||a.id.localeCompare(b.id))){if(o.order_date>p.payment_date)continue;const due=totals(s,o).outstanding;if(due<=0||left<=0)continue;const amount=Math.min(left,due);rows.push({order_id:o.id,order_date:o.order_date,feed_name:o.feed_name,before:due,amount,after:round(due-amount),version:o.version});left=round(left-amount)}if(!rows.length)throw Error('NO_PAYABLE_ORDERS');const applied=round(p.amount-left),balance=availableCash(s,p.batch_id,p.payment_date),plan={rows,requested:p.amount,applied,unapplied:left,available_cash:balance,can_pay:balance>=applied,batch_id:p.batch_id,payment_date:p.payment_date};return{...plan,fingerprint:JSON.stringify(plan)}}
export function demoWrite(s,name,args){prepareDemo(s);const p=args.p_data;switch(name){
case 'feed_save_order':{const o=s.orders.find(x=>x.id===p.id);if(o){if(o.version!==p.version)throw Error('VERSION_CONFLICT');if(s.claims.some(x=>x.order_id===p.id)||s.payments.some(x=>x.order_id===p.id)||s.allocations.some(x=>x.order_id===p.id)||o.paid_total>0){if(['feed_name','order_date','quantity','unit','unit_price','kg_per_unit','total'].some(k=>(o[k]??null)!==(p[k]??null)))throw Error('LINKED_ORDER_LOCKED')}Object.assign(o,p,{version:o.version+1});return o;}const r={...p,version:1,paid_total:0,is_visible:true};s.orders.push(r);return r;}
case 'feed_allocate':{const src=source(s,p.order_id,p.source_claim_id);if(!(p.quantity>0)||p.quantity>src.available)throw Error('INSUFFICIENT_CENTRAL_STOCK');if(p.allocation_date<src.available_from)throw Error('INVALID_DATE');const a={...p,id:id(),feed_name:src.feed_name,unit:src.unit,assigned_cost:round(p.quantity*p.unit_price)};s.allocations.push(a);return a;}
case 'feed_claim':{const src=source(s,p.order_id,p.source_claim_id);if(p.return_qty>src.available)throw Error('INSUFFICIENT_CENTRAL_STOCK');if(p.return_qty+p.replacement_qty<=0)throw Error('INVALID_CLAIM');const rv=round(p.return_qty*src.unit_price),nv=round(p.replacement_qty*p.replacement_unit_price);if(totals(s,s.orders.find(o=>o.id===p.order_id)).net_total+nv-rv<0)throw Error('CLAIM_EXCEEDS_INVOICE_VALUE');const c={...p,id:id(),return_unit_price:src.unit_price,return_value:rv,replacement_value:nv};s.claims.push(c);return c;}
case 'feed_pay':{const plan=previewPayment(s,p);if(plan.fingerprint!==args.p_expected)throw Error('PAYMENT_PREVIEW_CHANGED');if(!plan.can_pay)throw Error('INSUFFICIENT_BATCH_CASH');const group=id();for(const row of plan.rows){s.payments.push({id:id(),order_id:row.order_id,batch_id:p.batch_id,payment_date:p.payment_date,payment_method:p.payment_method,note:p.note,amount:row.amount,payment_group_id:group});s.cash.push({id:id(),batch_id:p.batch_id,cash_date:p.payment_date,kind:'feed_payment',amount:-row.amount,note:p.note})}return{...plan,payment_group_id:group,saved:true};}
case 'cash_record':{if(!(p.amount>0))throw Error('INVALID_CASH');if(p.kind==='opening'&&s.cash.some(c=>c.batch_id===p.batch_id))throw Error('OPENING_MUST_BE_FIRST');const outgoing=['expense','withdrawal','savings_transfer'].includes(p.kind);if(outgoing&&availableCash(s,p.batch_id,p.cash_date)<p.amount)throw Error('INSUFFICIENT_BATCH_CASH');const c={...p,id:id(),amount:p.amount*(outgoing?-1:1)};s.cash.push(c);return c;}
case 'batch_save':{const old=s.batches.find(b=>b.id===p.id);if(old){if((old.version||1)!==p.version)throw Error('VERSION_CONFLICT');if(old.species_id!==p.species_id)throw Error('SPECIES_LOCKED');Object.assign(old,p,{version:p.version+1});return old;}const b={...p,version:1};s.batches.push(b);return b;}
default:throw Error('UNKNOWN_DEMO_ACTION');}}
