// Original SVG line icons: consistent geometry, no platform-only symbol font.
const paths={home:'M3 10 12 3l9 7M5 9v12h5v-7h4v7h5V9',farm:'M3 21V9l9-6 9 6v12M8 21v-8h8v8M3 10h18',feed:'M6 3h12v18l-3-2-3 2-3-2-3 2V3ZM9 7h6M9 11h6M9 15h3',analytics:'M4 3v18h17M8 16v-5M13 16V7M18 16v-9',finance:'M3 6h16v4M3 6v14h18V10H7a4 4 0 0 1-4-4ZM16 14h5',prices:'M3 4h8l10 10-7 7L3 10V4ZM7 7h.01',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',more:'M5 12h.01M12 12h.01M19 12h.01',left:'m14 6-6 6 6 6',right:'m10 6 6 6-6 6',close:'m6 6 12 12M18 6 6 18',add:'M12 4v16M4 12h16',edit:'m14 5 5 5M4 20l4-1L21 6l-4-4L4 15v5Z',save:'M5 3h12l4 4v14H3V3h2ZM7 3v6h10V3M7 21v-8h10v8',logout:'M9 4H4v16h5M10 12h11m-4-4 4 4-4 4',reset:'M4 9a8 8 0 1 1 0 6M4 4v5h5'};
export function icon(name){return `<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="${paths[name]||paths.more}"/></svg>`}
const primary=new Set(['home','farm','feed','finance']);
export function navigation(nav,route){const link=([r,,label],extra='')=>`<a href="#${r}" class="nav-item ${extra} ${route===r?'selected':''}" ${route===r?'aria-current="page"':''} title="${label}">${icon(r)}<span class="nav-label">${label}</span></a>`;return `<nav class="app-nav glass-surface" aria-label="โมดูลหลัก">${nav.map(n=>link(n,primary.has(n[0])?'nav-primary':'nav-secondary')).join('')}<button type="button" id="moreNav" class="nav-item nav-more ${!primary.has(route)?'selected':''}" aria-label="เมนูเพิ่มเติม" aria-haspopup="dialog">${icon('more')}<span class="nav-label">เพิ่มเติม</span></button></nav><dialog id="moduleMenu" class="module-menu" aria-labelledby="moduleMenuTitle"><header><h2 id="moduleMenuTitle">พื้นที่ทำงานเพิ่มเติม</h2><button type="button" class="icon-button glass-surface" id="closeNav" aria-label="ปิดเมนู">${icon('close')}</button></header><div class="more-links">${nav.filter(n=>!primary.has(n[0])).map(n=>link(n)).join('')}</div></dialog>`}
export function bindNavigation(){const menu=document.querySelector('#moduleMenu'),more=document.querySelector('#moreNav');more?.addEventListener('click',()=>menu.showModal());document.querySelector('#closeNav')?.addEventListener('click',()=>menu.close());menu?.addEventListener('click',e=>{if(e.target===menu){const r=menu.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)menu.close()}});menu?.addEventListener('close',()=>more.focus());}
export function decorateActions(root=document){
 const configs=[['#prevMonth','left',true],['#nextMonth','right',true],['#orderForm button','add'],['#dealForm button','edit'],['#eggForm button','save'],['#eventForm button','add'],['#planForm button','save'],['#logout','logout'],['#reset','reset']];
 for(const [selector,name,iconOnly]of configs){const el=root.querySelector(selector);if(!el)continue;const text=el.textContent;el.classList.add(iconOnly?'icon-button':'action-button');if(iconOnly){el.classList.add('glass-surface');el.innerHTML=icon(name)}else el.innerHTML=icon(name)+`<span>${text}</span>`;}
}
